anime/urls.py
from django.contrib import admin
from django.urls import path
from .views import AnimeListView, OneAnimeView, AnimeAddRating, create_rating
# from static.views import anime_detail, create_comment ТЕСТ ЧАТ ГПТ


app_name = 'animepage'

urlpatterns = [
    path('', AnimeListView.as_view(), name='anime'),
    path('category/<int:category_id>', AnimeListView.as_view(), name='filter_anime'),
    path('<int:pk>/', OneAnimeView.as_view(), name='one_anime'),
    # path('<int:anime_id>/', anime_detail, name='one_anime'), ТЕСТ ЧАТ ГПТ
    # path('<int:anime_id>/comment', create_comment, name='create_comment'), ТЕСТ ЧАТ ГПТ
    path('<int:pk>/rating', create_rating, name='create_rating'),
    # path('add_rating/<int:pk>', AnimeAddRating.as_view(), name='rating'), ТЕСТ ЧАТ ГПТ
]

films/urls.py
from django.contrib import admin
from django.urls import path
from .views import FilmsListView, OneFilmView, AddFilmsRating, create_rating

app_name = 'filmspage'

urlpatterns = [
    path('', FilmsListView.as_view(), name='films'),
    path('category/<int:category_id>', FilmsListView.as_view(), name='film_filter'),
    path('<int:pk>', OneFilmView.as_view(), name='one_film'),
    path('<int:pk>/rating', create_rating, name='create_rating'),
    # path('add_rating/<int:pk>', AddFilmsRating.as_view(), name='rating'),

]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('start.urls', namespace='basepage')),
    path('films/', include('films.urls', namespace='filmspage')),
    path('anime/', include('anime.urls', namespace='animepage')),
    path('profile/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

start/urls.py
from django.contrib import admin
from django.urls import path, include
from start.views import IndexView, TopsWeek
from films.views import FilmsListView
from anime.views import AnimeListView
app_name = 'basepage'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('tops', TopsWeek.as_view(), name='top_week'),
                ]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import UserRegistrationView, LoginProfileView, UserProfileView, logout

app_name = 'users'

urlpatterns = [
    path('<int:pk>', login_required(UserProfileView.as_view()), name='profile'),
    path('registration/', UserRegistrationView.as_view(), name='register'),
    path('login/', LoginProfileView.as_view(), name='login'),
    path('logout/', logout.as_view(), name='logout'),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from anime.models import Anime
from films.models import Films


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    is_verified_emails = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.id}'


class CommentsAnime(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор комментария', blank=True, null=True)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, verbose_name='Комментируемое аниме',
                              blank=True, null=True, related_name='CommentsAnime_Anime')
    create_date = models.DateTimeField(auto_now=True)
    comment = models.TextField(max_length=400)


    def __str__(self):
        return f'{self.comment}'


class CommentsFilm(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор комментария', blank=True, null=True)
    film = models.ForeignKey(Films, on_delete=models.CASCADE, verbose_name='Комментируемый фильм',
                              blank=True, null=True, related_name='CommentsFilm_Films')
    create_date = models.DateTimeField(auto_now=True)
    comment = models.TextField(max_length=400)


    def __str__(self):
        return f'{self.comment}'


class RatingAnime(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор рейтинга', blank=True, null=True)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, verbose_name='Оцениваемое аниме',
                              blank=True, null=True, related_name='RatingAnime_Anime')
    create_date = models.DateTimeField(auto_now=True)
    rating = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], blank=True, null=True)

    def __str__(self):
        return f'{self.rating}'

    class Meta:
        ordering = ['-rating']
# class RatingStarAnime(models.Model):
#     value = models.SmallIntegerField('Значение', default=0)
#     def __str__(self):
#         return f'{self.value}'
#     class Meta:
#         verbose_name = 'Звезды рейтинга'
#         verbose_name_plural = 'Звезды рейтинга'
#         ordering = ['-value']

class RatingFilms(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор комментария', blank=True, null=True)
    film = models.ForeignKey(Films, on_delete=models.CASCADE, verbose_name='Комментируемый фильм',
                              blank=True, null=True, related_name='RatingFilms_Films')
    create_date = models.DateTimeField(auto_now=True)
    rating = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], blank=True, null=True)

    def __str__(self):
        return f'{self.rating}'

    class Meta:
        ordering = ['-rating']

users/forms.py
import uuid
from datetime import timedelta

from django import forms
from django.forms import Textarea
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.utils.timezone import now

from users.models import User, CommentsAnime, CommentsFilm, RatingAnime, RatingFilms


class UserRegistrationForm(UserCreationForm):

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите логин'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введите почтовый адрес'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Повторите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'input_class'

class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль',
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'input_class'


class UserProfileForm(UserChangeForm):

    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    image = forms.ImageField(widget=forms.FileInput(), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={
        'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'input_class'
        self.fields['image'].widget.attrs['class'] = 'image'

class CommentFormAnime(forms.ModelForm):

    class Meta:
        model = CommentsAnime
        fields = ('comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comment'].widget = Textarea(attrs={'rows':5})


class CommentFormFilm(forms.ModelForm):

    class Meta:
        model = CommentsFilm
        fields = ('comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comment'].widget = Textarea(attrs={'rows':5})


class RatingAnimeForm(forms.ModelForm):

    class Meta:
        model = RatingAnime
        fields = ('rating',)


class RatingFilmForm(forms.ModelForm):

    class Meta:
        model = RatingFilms
        fields = ('rating',)

users/views.py
from django.shortcuts import render
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from .models import User, CommentsAnime
from django.contrib.auth.views import LoginView, LogoutView
from django.views import View
from .forms import UserRegistrationForm, UserProfileForm, UserLoginForm, CommentFormAnime
# Create your views here.


class UserRegistrationView(CreateView):

    model = User
    form_class = UserRegistrationForm
    template_name = 'register.html'
    success_url = reverse_lazy('basepage:index')


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'profile.html'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))


class LoginProfileView(LoginView):
    template_name = 'login.html'
    form_class = UserLoginForm


class logout(View):

    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect(reverse('basepage:index'))

users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block title %} Авторизация {% endblock %}
{% block header %}
<div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
            </div>
        <div class="panel" >
            <div class="panel-text" >
                <h2>Топ-недели</h2>
                <hr>
                <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                <hr>
                <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                <hr>
                <h2>Личный кабинет</h2>
            </div>
</div>
</div>
{% endblock %}
{% block content %}
    <form action="{% url 'users:login' %}" class="form"  method="post">
        {% csrf_token %}
            <div class="form-row">
                <div class="rows">
                    <label for="{{ form.username.id_for_label }}"></label>
                        {{ form.username }}
                </div>
                <div class="rows">
                    <label for="{{ form.password.id_for_label }}"></label>
                        {{ form.password }}
                </div>
                <div>
                    <input class="submit_class" type="submit" value="Авторизоваться">
                    <div class="un_acc"><a class="a_un_acc" href="{% url 'users:register' %}">Нет аккаунта? Зарегистрируйся!</a></div>
                </div>
            </div>
    </form>
{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}
{% block title %} Регистрация {% endblock %}
{% block header %}
<div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
                {% if user.is_authenticated %}
                <h2 class="logout"><a href="{% url 'users:logout' %}">
                        Выйти из аккаунта
                    </a></h2> {% endif %}
            </div>
        <div class="panel" >
            <div class="panel-text" >
                <h2><a href="{% url 'basepage:top_week' %}">Топ-недели</a></h2>
                <hr>
                <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                <hr>
                <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                <hr>
                <h2>{% if user.is_authenticated %} {{user.first_name }} {% else %} Войти {% endif %}</h2>
            </div>
</div>
</div>
{% endblock %}
{% block content %}
<div class="profile">
    <img width="100" height="100"
                     src="{% if user.image %} {{user.image.url}}{% endif %}"
                     class="img-thumbnail">
    <form action="{% url 'users:profile' user.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="form-row">
                <div class="rows">
                    <label for="{{ form.first_name.id_for_label }}"></label>
                        {{ form.first_name }}
                </div>
                <div class="rows">
                    <label for="{{ form.last_name.id_for_label }}"></label>
                        {{ form.last_name }}
                </div>
                <div class="rows">
                    <label for="{{ form.image.id_for_label }}"></label>
                        {{ form.image }}
                </div>
                <div class="rows">
                    <label for="{{ form.username.id_for_label }}"></label>
                        {{ form.username }}
                </div>
                <div class="rows">
                    <label for="{{ form.email.id_for_label }}"></label>
                        {{ form.email }}
                </div>
                <input class="submit_class" type="submit" value="Сохранить">
            </div>
    </form>
</div>
{% endblock %}

users/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}
{% block title %} Регистрация {% endblock %}
{% block header %}
<div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
            </div>
        <div class="panel" >
            <div class="panel-text" >
                <h2>Топ-недели</h2>
                <hr>
                <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                <hr>
                <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                <hr>
                <h2>Личный кабинет</h2>
            </div>
</div>
</div>
{% endblock %}
{% block content %}
<div class="register_form">
    <form action="{% url 'users:register' %}" class="form" method="post" >
        {% csrf_token %}
        <div class="form-row">
            <div class="rows">
                <label for="{{ form.first_name.id_for_label }}"></label>
                    {{ form.first_name }}
            </div>
            <div class="rows">
                <label for="{{ form.last_name.id_for_label }}"></label>
                    {{ form.last_name }}
            </div>
            <div class="rows">
                <label for="{{ form.username.id_for_label }}"></label>
                    {{ form.username }}
            </div>
            <div class="rows">
                <label for="{{ form.email.id_for_label }}"></label>
                    {{ form.email }}
            </div>
            <div class="rows">
                <label for="{{ form.password1.id_for_label }}"></label>
                    {{ form.password1 }}
            </div>
            <div class="rows">
                <label for="{{ form.password2.id_for_label }}"></label>
                    {{ form.password2 }}
            </div>
            <div>
                <input class="submit_class" type="submit" value="Создать аккаунт">
            </div>

        </div>
    </form>
</div>
{% endblock %}