anime/urls.py
from django.contrib import admin
from django.urls import path
from .views import AnimeListView, OneAnimeView, AnimeAddRating, create_rating
# from static.views import anime_detail, create_comment ТЕСТ ЧАТ ГПТ


app_name = 'animepage'

urlpatterns = [
    path('', AnimeListView.as_view(), name='anime'),
    path('category/<int:category_id>', AnimeListView.as_view(), name='filter_anime'),
    path('<int:pk>/', OneAnimeView.as_view(), name='one_anime'),
    # path('<int:anime_id>/', anime_detail, name='one_anime'), ТЕСТ ЧАТ ГПТ
    # path('<int:anime_id>/comment', create_comment, name='create_comment'), ТЕСТ ЧАТ ГПТ
    path('<int:pk>/rating', create_rating, name='create_rating'),
    # path('add_rating/<int:pk>', AnimeAddRating.as_view(), name='rating'), ТЕСТ ЧАТ ГПТ
]

films/urls.py
from django.contrib import admin
from django.urls import path
from .views import FilmsListView, OneFilmView, AddFilmsRating, create_rating

app_name = 'filmspage'

urlpatterns = [
    path('', FilmsListView.as_view(), name='films'),
    path('category/<int:category_id>', FilmsListView.as_view(), name='film_filter'),
    path('<int:pk>', OneFilmView.as_view(), name='one_film'),
    path('<int:pk>/rating', create_rating, name='create_rating'),
    # path('add_rating/<int:pk>', AddFilmsRating.as_view(), name='rating'),

]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('start.urls', namespace='basepage')),
    path('films/', include('films.urls', namespace='filmspage')),
    path('anime/', include('anime.urls', namespace='animepage')),
    path('profile/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

start/urls.py
from django.contrib import admin
from django.urls import path, include
from start.views import IndexView, TopsWeek
from films.views import FilmsListView
from anime.views import AnimeListView
app_name = 'basepage'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('tops', TopsWeek.as_view(), name='top_week'),
                ]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import UserRegistrationView, LoginProfileView, UserProfileView, logout

app_name = 'users'

urlpatterns = [
    path('<int:pk>', login_required(UserProfileView.as_view()), name='profile'),
    path('registration/', UserRegistrationView.as_view(), name='register'),
    path('login/', LoginProfileView.as_view(), name='login'),
    path('logout/', logout.as_view(), name='logout'),
]

anime/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class AnimeCategory(models.Model):

    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Anime Categories'

    def __str__(self):
        return self.name



class Anime(models.Model):

    anime = models.CharField(max_length=30)
    studio = models.CharField(max_length=30)
    rating = models.PositiveIntegerField(blank=True, validators=[MaxValueValidator(100)])
    image = models.ImageField(upload_to='anime_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    category = models.ForeignKey(AnimeCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.anime}'

films/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class FilmsCategory(models.Model):

    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Films Categories'

    def __str__(self):
        return self.name


class Films(models.Model):

    cinema = models.CharField(max_length=30)
    producer = models.CharField(max_length=30)
    rating = models.PositiveIntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(100)])
    image = models.ImageField(upload_to='films_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    category = models.ForeignKey(FilmsCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.cinema}'

    class Meta:
        ordering = ['-rating']

start/models.py
from django.db import models

# Create your models here.

anime/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic import DetailView
from .models import Anime, AnimeCategory
from django.views.generic.edit import FormMixin
from users.forms import CommentFormAnime, RatingAnimeForm
from users.models import RatingAnime, CommentsAnime
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.


class AnimeListView(ListView):

    model = Anime
    template_name = 'anime.html'

    def get_queryset(self):
        queryset = super(AnimeListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        # if category_id == None:
        #     category_id = 3
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AnimeListView, self).get_context_data()
        context['categories'] = AnimeCategory.objects.all()
        return context


class OneAnimeView(FormMixin, DetailView):

    model = Anime
    template_name = 'one-anime.html'
    form_class = CommentFormAnime
    success_msg = 'Комментарий успешно добавлен'

    def get_success_url(self, **kwargs):
        return reverse_lazy('animepage:one_anime', kwargs={'pk': self.get_object().id})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.anime = self.get_object()
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        anime = Anime.objects.get(id=self.kwargs.get('pk'))
        context['rating_form'] = RatingAnimeForm()
        if RatingAnime.objects.filter(anime=anime):
            context['OneRatingAnime'] = RatingAnime.objects.get(Q(user=user) and Q(anime=anime))
            return context
        else:
            return context
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['RatForm'] = RatingAnime()
    #     return context


def create_rating(request, **kwargs):
    anime_id = kwargs.get('pk')
    if request.method == 'POST':
        anime = get_object_or_404(Anime, id=anime_id)
        user = request.user
        rating = request.POST.get('rating')
        rating_obj = RatingAnime.objects.filter(user=user, anime=anime)
        if rating_obj:
            rating_obj.update(rating=rating)
        else:
            rating = RatingAnime(anime=anime, user=user, rating=rating)
            rating.save()
        return redirect('animepage:one_anime', pk=anime_id)


class AnimeAddRating(CreateView):
    model = RatingAnime
    form_class = RatingAnimeForm
    template_name = 'rating-anime.html'
    success_url = 'animepage:anime'

    # def get_success_url(self, **kwargs):
    #     return reverse_lazy('animepage:anime', kwargs={'pk': self.get_object().id})

    def post(self, request, *args, **kwargs):
        # form = RatingAnimeForm(request.POST)
        user = self.request.user
        anime = Anime.objects.get(id=self.kwargs.get('pk'))
        form = self.get_form()
        if form.is_valid():
            RatingAnime.objects.update_or_create(
                user=user,
                anime=anime,
                # rating=int(request.POST.get('rating')),
                defaults={'rating': int(request.POST.get('rating'))}
            )
            print('5')
            return HttpResponseRedirect('/anime')
            # return self.form_valid(form)
        else:
            self.form_invalid(form)





    # def form_valid(self, form, **kwargs):
    #
    #     self.object = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.anime = Anime.objects.get(id=self.kwargs.get('pk'))
    #     self.object.save()
    #     return super().form_valid(form)



# class AddRating(View):
#
#     def get_user(self, request):
#         x_forward = request.META.get('user.id')
#         if x_forward:
#             iduser = int(x_forward)
#         else:
#             None
#         return iduser
#
#     def post(self, request):
#         form = RatingAnime(request.POST)
#         if form.is_valid():
#             RatingAnime.objects.update_or_create(
#                 anime=int(request.POST.get('anime.id')),
#                 user=self.get_user(request),
#                 # user=int(request.POST.get('user.id')),
#                 defaults={'rating_id': int(request.POST.get('rating'))}
#             )



    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.anime = self.request.anime
    #     self.object.save()
    #     return reverse_lazy('animepage:anime')


    # 1) Наследование классов, с помощью прошлого класса попробовать отобразить 2 формы
    # 2) Расширение шаблонов, отдельный шаблон в котором рейтинг
    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(OneListView, self).get_context_data()
    #     anime_id = self.kwargs.get('anime_id')
    #     context['anime'] = AnimeCategory.objects.get(anime_id)
    #     return context

    # def get_queryset(self):
    #     queryset = super(OneListView, self).get_queryset()
    #     anime_id = self.kwargs.get('anime_id')
    #     return queryset.filter(anime_id=anime_id)


# class CommentOneAnime(View):
#
#     def get(self, request, **kwargs):
#         anime_id = self.kwargs.get('anime_id')
#         context = {
#             'anime': Anime.objects.get(id=anime_id)
#         }
#         return render(request, 'one-film.html', context)
#
#     def post(self, request):
#
#         form = CommentsAnime()

films/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import FormView, CreateView
from django.views.generic.list import ListView
from .models import FilmsCategory, Films
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from users.forms import CommentFormFilm, RatingFilmForm
from users.models import RatingFilms
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q
# Create your views here.

class FilmsListView(ListView):

    model = Films
    template_name = 'films.html'


    def get_queryset(self):
        queryset = super(FilmsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FilmsListView, self).get_context_data()
        context['categories'] = FilmsCategory.objects.all()
        return context


class OneFilmView(FormMixin, DetailView):

    model = Films
    template_name = 'one-film.html'
    form_class = CommentFormFilm
    success_msg = 'Комментарий успешно добавлен'

    def get_success_url(self, **kwargs):
        return reverse_lazy('filmspage:one_film', kwargs={'pk': self.get_object().id})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.film = self.get_object()
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        film = Films.objects.get(id=self.kwargs.get('pk'))
        context['rating_form'] = RatingFilmForm()
        if RatingFilms.objects.filter(film=film):
            context['OneRatingFilm'] = RatingFilms.objects.get(Q(user=user) and Q(film=film))
            return context
        else:
            return context


class AddFilmsRating(CreateView):
    model = RatingFilms
    form_class = RatingFilmForm
    template_name = 'rating-film.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('filmspage:films')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.form_invalid(form)

    def form_valid(self, form, **kwargs):

        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.film = Films.objects.get(id=self.kwargs.get('pk'))
        self.object.save()
        return super().form_valid(form)


def create_rating(request, **kwargs):
    cinema_id = kwargs.get('pk')
    if request.method == 'POST':
        cinema = get_object_or_404(Films, id=cinema_id)
        user = request.user
        rating = request.POST.get('rating')
        rating_obj = RatingFilms.objects.filter(user=user, film=cinema)
        if rating_obj:
            rating_obj.update(rating=rating)
        else:
            rating = RatingFilms(user=user, film=cinema, rating=rating)
            rating.save()
        return redirect('filmspage:one_film', pk=cinema_id)

# class FilmAddRating(CreateView):
#     model = RatingFilms
#     form_class = RatingFilmForm
#     template_name = 'rating-film.html'
#     success_url = 'filmspage:films'
#
#     # def get_success_url(self, **kwargs):
#     #     return reverse_lazy('animepage:anime', kwargs={'pk': self.get_object().id})
#
#     def post(self, request, *args, **kwargs):
#         user = self.request.user
#         film = Films.objects.get(id=self.kwargs.get('pk'))
#         form = self.get_form()
#         if form.is_valid():
#             RatingFilms.objects.update_or_create(
#                 user=user,
#                 film=film,
#                 # rating=int(request.POST.get('rating')),
#                 defaults={'rating': int(request.POST.get('rating'))}
#             )
#             return HttpResponseRedirect('/films')
#             # return self.form_valid(form)
#         else:
#             self.form_invalid(form)

start/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views import View
from anime.models import Anime
from films.models import Films
from users.models import RatingAnime, RatingFilms
# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'


class TopsWeek(View):

    def get(self, request):

        a = RatingAnime.objects.filter(rating__gt=80)
        b = RatingFilms.objects.filter(rating__gt=80)
        context = {
            'Films': b,
            'Anime': a,
        }
        return render(request, 'tops-week.html', context)

start/templates/anime.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/anime.css' %}">
{% endblock %}
{% block title %} Anime {% endblock %}
{% block header %}
<div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
            </div>
        <div class="panel" >
            <div class="panel-text" >
                <h2><a href="{% url 'basepage:top_week' %}">Топ-недели</a></h2>
                <hr>
                <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                <hr>
                <h2>Аниме</h2>
                <hr>
                <h2><a href="
                    {% if user.is_authenticated %} {% url 'users:profile' user.id %} {% else %} {% url 'users:login' %} {% endif %}
                                    ">
                        {% if user.is_authenticated %} {{user.username }} {% else %} Войти {% endif %}
                    </a></h2>
            </div>
</div>
</div>
{% endblock %}
{% block content %}
    <div class="categories">
        {% for category in categories %}
        <p class="p-cat"><a href="{% url 'animepage:filter_anime' category.id %}">  {{ category.name }} </a></p>
        {% endfor %}
    </div>
<div class="main">
    <div class="hello">
             <h3>
                 Аниме: <hr> Поделитесь своим мнением о фильме или аниме которое вы посмотрели
             </h3>
        <div class="anime">{% for anime in object_list %}
                <div class="one-anime">
            <a href="{% url 'animepage:one_anime' anime.id %}"> <img class="picture" src="/media/{{ anime.image }}"></a>
            <h3> {{ anime.anime }}</h3>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

start/templates/films.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block title %} Начало {% endblock %}
{% block header %}
        <div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
            </div>
            <div class="panel" >
                <div class="panel-text" >
                    <h2><a href="{% url 'basepage:top_week' %}">Топ-недели</a></h2>
                    <hr>
                    <h2> Фильмы</h2>
                    <hr>
                    <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                    <hr>
                    <h2><a href="
                    {% if user.is_authenticated %} {% url 'users:profile' user.id %} {% else %} {% url 'users:login' %} {% endif %}
                                    ">
                        {% if user.is_authenticated %} {{user.username }} {% else %} Войти {% endif %}
                    </a></h2>
                </div>
            </div>
        </div>
{% endblock %}
{% block content %}
<div class="categories">
        {% for category in categories %}
        <p class="p-cat"><a href="{% url 'filmspage:film_filter' category.id %}">  {{ category.name }} </a></p>
        {% endfor %}
    </div>
<div class="main">
    <div class="hello">
             <h3>
                 Фильмы: <hr> Поделитесь своим мнением о фильме или аниме которое вы посмотрели
             </h3>
        <div class="anime">{% for film in object_list %}
                <div class="one-anime">
            <a href="{% url 'filmspage:one_film' film.id %}"> <img class="picture" src="/media/{{ film.image }}"></a>
            <h3> {{ film.cinema }}</h3>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

start/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block title %} Начало {% endblock %}
    {% block header %}
            <div class="header">
                <div class="header-title">
                        <h1>Синемария - форум по обсуждению фильмов и аниме</h1>
                </div>
                    <div class="panel" >
                        <div class="panel-text">
                        <h2><a href="{% url 'basepage:top_week' %}">Топ-недели</a></h2>
                        <hr>
                        <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                        <hr>
                        <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                        <hr>
                        <h2><a href="{% if user.is_authenticated %} {% url 'users:profile' user.id %} {% else %} {% url 'users:login' %} {% endif %}">
                            {% if user.is_authenticated %} Личный кабинет | {{user.username }} {% else %} Личный кабинет | Войти {% endif %}
                        </a></h2>
                </div>
            </div>
                </div>
    {% endblock %}
{% block content %}
<div class="main">
    <div class="hello">
             <h3>
                 Добро пожаловать! <hr> Поделитесь своим мнением о фильме или аниме которое вы посмотрели
             </h3>
    </div>
</div>

{% endblock %}

start/templates/tops-week.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block title %} Начало {% endblock %}
{% block header %}
        <div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
            </div>
            <div class="panel" >
                <div class="panel-text" >
                    <h2>Топ-недели</h2>
                    <hr>
                    <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                    <hr>
                    <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                    <hr>
                    <h2><a href="
                    {% if user.is_authenticated %} {% url 'users:profile' user.id %} {% else %} {% url 'users:login' %} {% endif %}
                                    ">
                        {% if user.is_authenticated %} {{user.username }} {% else %} Войти {% endif %}
                    </a></h2>
                </div>
            </div>
        </div>
{% endblock %}
{% block content %}
<div class="categories">
        {% for category in categories %}
        <p class="p-cat"><a href="{% url 'filmspage:film_filter' category.id %}">  {{ category.name }} </a></p>
        {% endfor %}
    </div>
<div class="main">
    <div class="hello">
             <h3>
                 Поделитесь своим мнением о фильме или аниме которое вы посмотрели<hr> Топы недели: Фильмы
             </h3>
        <div class="anime">{% for film in Films %}
                <div class="one-anime">
            <a href="{% url 'filmspage:one_film' film.film.id %}"> <img class="picture" src="/media/{{ film.film.image }}"></a>
            <h3> {{ film.cinema }}</h3>
                </div>
            {% endfor %}
                Топы недели: Аниме
                    {% for anime in Anime %}
                <div class="one-anime">
            <a href="{% url 'animepage:one_anime' anime.anime.id %}"> <img class="picture" src="/media/{{ anime.anime.image }}"></a>
            <h3> {{ anime.anime }}</h3>
                </div>
                {% endfor %}
        </div>
    </div>
</div>
{% endblock %}