anime/urls.py
from django.contrib import admin
from django.urls import path
from .views import AnimeListView, OneAnimeView, AnimeAddRating, create_rating
# from static.views import anime_detail, create_comment ТЕСТ ЧАТ ГПТ


app_name = 'animepage'

urlpatterns = [
    path('', AnimeListView.as_view(), name='anime'),
    path('category/<int:category_id>', AnimeListView.as_view(), name='filter_anime'),
    path('<int:pk>/', OneAnimeView.as_view(), name='one_anime'),
    # path('<int:anime_id>/', anime_detail, name='one_anime'), ТЕСТ ЧАТ ГПТ
    # path('<int:anime_id>/comment', create_comment, name='create_comment'), ТЕСТ ЧАТ ГПТ
    path('<int:pk>/rating', create_rating, name='create_rating'),
    # path('add_rating/<int:pk>', AnimeAddRating.as_view(), name='rating'), ТЕСТ ЧАТ ГПТ
]

films/urls.py
from django.contrib import admin
from django.urls import path
from .views import FilmsListView, OneFilmView, AddFilmsRating, create_rating

app_name = 'filmspage'

urlpatterns = [
    path('', FilmsListView.as_view(), name='films'),
    path('category/<int:category_id>', FilmsListView.as_view(), name='film_filter'),
    path('<int:pk>', OneFilmView.as_view(), name='one_film'),
    path('<int:pk>/rating', create_rating, name='create_rating'),
    # path('add_rating/<int:pk>', AddFilmsRating.as_view(), name='rating'),

]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('start.urls', namespace='basepage')),
    path('films/', include('films.urls', namespace='filmspage')),
    path('anime/', include('anime.urls', namespace='animepage')),
    path('profile/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

start/urls.py
from django.contrib import admin
from django.urls import path, include
from start.views import IndexView, TopsWeek
from films.views import FilmsListView
from anime.views import AnimeListView
app_name = 'basepage'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('tops', TopsWeek.as_view(), name='top_week'),
                ]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import UserRegistrationView, LoginProfileView, UserProfileView, logout

app_name = 'users'

urlpatterns = [
    path('<int:pk>', login_required(UserProfileView.as_view()), name='profile'),
    path('registration/', UserRegistrationView.as_view(), name='register'),
    path('login/', LoginProfileView.as_view(), name='login'),
    path('logout/', logout.as_view(), name='logout'),
]

films/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class FilmsCategory(models.Model):

    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Films Categories'

    def __str__(self):
        return self.name


class Films(models.Model):

    cinema = models.CharField(max_length=30)
    producer = models.CharField(max_length=30)
    rating = models.PositiveIntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(100)])
    image = models.ImageField(upload_to='films_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    category = models.ForeignKey(FilmsCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.cinema}'

    class Meta:
        ordering = ['-rating']

films/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import FormView, CreateView
from django.views.generic.list import ListView
from .models import FilmsCategory, Films
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from users.forms import CommentFormFilm, RatingFilmForm
from users.models import RatingFilms
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q
# Create your views here.

class FilmsListView(ListView):

    model = Films
    template_name = 'films.html'


    def get_queryset(self):
        queryset = super(FilmsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FilmsListView, self).get_context_data()
        context['categories'] = FilmsCategory.objects.all()
        return context


class OneFilmView(FormMixin, DetailView):

    model = Films
    template_name = 'one-film.html'
    form_class = CommentFormFilm
    success_msg = 'Комментарий успешно добавлен'

    def get_success_url(self, **kwargs):
        return reverse_lazy('filmspage:one_film', kwargs={'pk': self.get_object().id})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.film = self.get_object()
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        film = Films.objects.get(id=self.kwargs.get('pk'))
        context['rating_form'] = RatingFilmForm()
        if RatingFilms.objects.filter(film=film):
            context['OneRatingFilm'] = RatingFilms.objects.get(Q(user=user) and Q(film=film))
            return context
        else:
            return context


class AddFilmsRating(CreateView):
    model = RatingFilms
    form_class = RatingFilmForm
    template_name = 'rating-film.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('filmspage:films')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.form_invalid(form)

    def form_valid(self, form, **kwargs):

        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.film = Films.objects.get(id=self.kwargs.get('pk'))
        self.object.save()
        return super().form_valid(form)


def create_rating(request, **kwargs):
    cinema_id = kwargs.get('pk')
    if request.method == 'POST':
        cinema = get_object_or_404(Films, id=cinema_id)
        user = request.user
        rating = request.POST.get('rating')
        rating_obj = RatingFilms.objects.filter(user=user, film=cinema)
        if rating_obj:
            rating_obj.update(rating=rating)
        else:
            rating = RatingFilms(user=user, film=cinema, rating=rating)
            rating.save()
        return redirect('filmspage:one_film', pk=cinema_id)

# class FilmAddRating(CreateView):
#     model = RatingFilms
#     form_class = RatingFilmForm
#     template_name = 'rating-film.html'
#     success_url = 'filmspage:films'
#
#     # def get_success_url(self, **kwargs):
#     #     return reverse_lazy('animepage:anime', kwargs={'pk': self.get_object().id})
#
#     def post(self, request, *args, **kwargs):
#         user = self.request.user
#         film = Films.objects.get(id=self.kwargs.get('pk'))
#         form = self.get_form()
#         if form.is_valid():
#             RatingFilms.objects.update_or_create(
#                 user=user,
#                 film=film,
#                 # rating=int(request.POST.get('rating')),
#                 defaults={'rating': int(request.POST.get('rating'))}
#             )
#             return HttpResponseRedirect('/films')
#             # return self.form_valid(form)
#         else:
#             self.form_invalid(form)

films/templates/one-film.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block title %} Films {% endblock %}
{% block header %}
<div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
            </div>
        <div class="panel" >
            <div class="panel-text" >
                <h2>Топ-недели</h2>
                <hr>
                <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                <hr>
                <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                <hr>
                <h2><a href="
                    {% if user.is_authenticated %} {% url 'users:profile' user.id %}
                    {% else %} {% url 'users:login' %} {% endif %}">
                        {% if user.is_authenticated %} {{user.username }} {% else %} Войти {% endif %}
                    </a></h2>
            </div>
</div>
</div>
{% endblock %}
{% block content %}
    <div class="object">
        <img class="picture" src="/media/{{ films.image }}">
        <h3>{{ films.cinema }} | Рейтинг сайта: {{ films.rating }} | {% if user.is_authenticated %} {% if OneRatingFilm %} Ваша оценка:
            {{OneRatingFilm}} | Изменить оценку:
                    <form action="{% url 'filmspage:create_rating' films.id %}" method="post" >
                        {% csrf_token %}
                            <div class="comms">
                                {{ rating_form }}
                            </div>
                        <button type="submit">Изменить оценку</button>
                    </form>
            {% else %} Оценить:
                            <form action="{% url 'filmspage:create_rating' films.id %}" method="post" >
                                {% csrf_token %}
                                    <div class="comms">
                                        {{ rating_form }}
                                     </div>
                                <button type="submit">Добавить оценку</button>
                            </form> </h3>
                        {% endif %}
        {% endif %}
    </div>

    </form>
<h2> Комментарии пользователей: ({{films.CommentsFilm_Films.all.count}})</h2>
        {% for comment in films.CommentsFilm_Films.all %}
        <hr>
        {{ comment.user.username }}: {{ comment }}
        {% endfor %}
    <form  method="post">
        {% csrf_token %}

            <div class="comms">
                    {{ form }}
            </div>
        <button type="submit">Добавить комментарий</button>
    </form>

{% endblock %}

films/templates/rating-film.html
{% extends 'base.html' %}
{% load static %}
{% block css_add %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block title %} Anime {% endblock %}
{% block header %}
<div class="header">
            <div class="header-title">
                <h1><a href="{% url 'basepage:index' %}">Синемария - форум по обсуждению фильмов и аниме</a></h1>
            </div>
        <div class="panel" >
            <div class="panel-text" >
                <h2>Топ-недели</h2>
                <hr>
                <h2><a href="{% url 'filmspage:films' %}"> Фильмы</a></h2>
                <hr>
                <h2><a href="{% url 'animepage:anime' %}">Аниме</a></h2>
                <hr>
                <h2><a href="
                    {% if user.is_authenticated %} {% url 'users:profile' user.id %}
                    {% else %} {% url 'users:login' %} {% endif %}">
                        {% if user.is_authenticated %} {{user.username }} {% else %} Войти {% endif %}
                    </a></h2>
            </div>
</div>
</div>
{% endblock %}
{% block content %}
  <div class="rating">    <h2>
        Оставьте ваш рейтинг:
    </h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-style">
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit">Отправить</button></div>
{% endblock %}